import 'package:get/get.dart';
class MyLocalization implements Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>{
    "ar":{"1":"الصفحة الرئيسية",
      "2":"عربي",
      "3":"انكليزي",
      "4":"مرحبًا حمزة ",
      "5":"ابحث عن أفضل طبيب لك",
      "6":"عيادات",
      "7":"تخصصات",
      "8":"اسم العيادة ",
      "9":"عرض الملف الشخصي",
      "10":"عرض الأطباء",
      "11":"الاسم",
      "12":"My profile",
      "13":"Archive",
      "14":"Settings ",
      "15":"Appointments ",
      "16":"Notifications ",
      "17":"Message",
      "18":"Clinic ",
      "19":"Doctors ",
      "20":"Doctors in clinic",
      "21":"Clinic number",
      "22":"Address",
      "23":"Damascus",
      "24":"Syria",
      "25":"Rate us! ",
      "26":"General",
      "27":"Find your doctor",
      "28":"Doctor info",
      "29":"Doctor name",
      "30":"Doctor number",
      "31":"Experience ",
      "32":"+3 years",
      "33":"Description",
      "34":"Anything you want to add",
      "35":"Make appointment",
      "36":"",
      "37":"",
      "38":"",
      "39":"",
      "40":"",
      "41":"",
      "42":"",

    },
    "en":{"1":"Home",
      "2":"Arabic",
      "3":"English",
  "4":"Hi Hamza ",
  "5":"Find the best doctor for you ",
  "6":"Clinics ",
  "7":"Specialities",
  "8":"Clinic name ",
  "9":"View profile",
  "10":"View doctors",
  "11":"Name",
  "12":"My profile",
  "13":"Archive",
  "14":"Settings ",
  "15":"Appointments ",
  "16":"Notifications ",
  "17":"Message",
  "18":"Clinic ",
  "19":"Doctors ",
  "20":"Doctors in clinic",
  "21":"Clinic number",
  "22":"Address",
  "23":"Damascus",
  "24":"Syria",
  "25":"Rate us! ",
  "26":"General",
  "27":"Find your doctor",
  "28":"Doctor info",
  "29":"Doctor name",
  "30":"Doctor number",
  "31":"Experience ",
  "32":"+3 years",
  "33":"Description",
  "34":"Anything you want to add",
  "35":"Make appointment",
      "36":"",
      "37":"",
      "38":"",
      "39":"",
      "40":"",
      "41":"",
      "42":"",



    },
  } ;

}